baseURL = "https://betterthan.gold/"
languageCode = "en-us"
title = "Getting off zero"
theme = "ananke"
publishDir = "docs"
show_reading_time = true

SectionPagesMenu = "main"
Paginate = 3

[params]
  favicon = ""
  site_logo = ""
  description = "Acquire bitcoin at any cost."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/bitcoin.jpg"
  recent_posts_number = 5